"""empty message

Revision ID: 96b3dfb37946
Revises: 08d147c4b6e6
Create Date: 2020-01-04 00:03:47.264275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b3dfb37946'
down_revision = '08d147c4b6e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_link',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('link', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration_link')
    # ### end Alembic commands ###
